name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    name: "node:${{ matrix.node-version }} php:${{ matrix.php-version }} ${{ matrix.os }}"
    strategy:
      matrix:
        node-version:
          - 16
          - 18
        php-version:
          - "8.1"
        os:
          - "ubuntu-18.04"
          - "ubuntu-20.04"
          - "ubuntu-22.04"
        exclude:
          - os: ubuntu-18.04
            node-version: 18
          - os: ubuntu-20.04
            node-version: 18

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Execute tests
        run: vendor/bin/phpunit

      ##

      - run:  ./artisan config:cache
      - run:  ./artisan route:cache
      - run:  ./artisan schedule:list
      - run:  ./artisan event:cache
      - run:  ./artisan view:cache
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --production
      - run: npm run build
